<?php

/**
 * @file
 * Defines common functionality for all accounting modules.
 */

/**
 * Implements hook_theme().
 */
function accounting_theme($existing, $type, $theme, $path) {
  return [
    'accounting_dashboard_management_links' => [
      'variables' => [
        'links' => [],
      ],
    ],
    'accounting_dashboard_accounts_form' => [
      'variables' => [
        'form' => [],
      ],
    ],
    'accounting_dashboard_accounts_list' => [
      'variables' => [
        'accounts' => [],
        'links' => [],
      ],
    ],
    'accounting_dashboard_transactions_list' => [
      'variables' => [
        'transactions' => [],
        'links' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function accounting_views_data() {
  $data['accounts_table']['table']['group'] = t('Accounts');
  $data['accounts_table']['table']['base'] = [
    'field' => 'id',
    'title' => t('Account'),
    'help' => t('Account Chart.'),
  ];
  return $data;
}
